Add python/django invocations
saritasa-nest/saritasa-python-invocations pull request #2
Opened 2023-06-30 09:30 UTC by TheSuperiorStanislav

2023-07-05 09:07 UTC, ron8mcr requested changes

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +Run `makemigrations` command and chown created migrations.
Add note that `chown` required only for `docker` env

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +* `django_migrate_command` migrate command (Default: `migrate`)
Is there any use-case of custom `migrate` command? If not - I don't think that we need this setting

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +* `default_superuser_email` default email of superuser (Default: `root@root.com`)
Let's migrate to `root@localhost` to avoid accidental email sending

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +* `runserver_params` params for uvicorn runserver command (Default: `""`)
Let's remove mention of `uvicorn` as this is `django.run` task

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +* `shell_command` params for docker (Default: `shell_plus --ipython`)
Why just `docker` mentioned?

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +Open postgresql shell with credentials from either local or dev env.
It's simply calls `dbshell` management command, so there is no need to mention "postgres" explicitly

2023-07-05 09:07 UTC, ron8mcr commented on saritasa_invocations/django.py
> +        command="manage.py wait_for_database --stable 0",
Please add comment why `manage` function not used here

2023-07-05 09:07 UTC, ron8mcr commented on saritasa_invocations/django.py
Let's add notes to some commands that they depends on `django-probes/django-extensions`

2023-07-05 09:07 UTC, ron8mcr commented on saritasa_invocations/django.py
> +    # not used `manage` as for `runserver` command need to pass
But you used `manage` function later, please update comment

2023-07-05 09:07 UTC, ron8mcr commented on saritasa_invocations/fastapi.py
> +    # not used `manage` as for `runserver` command need to pass
Let's remove mention of `manage` as there is no such term in FastAPI/uvicorn

2023-07-05 09:07 UTC, ron8mcr commented on README.md
> +Run python command depending on `PYTHON_ENV` variable(`docker` or `local`).
Let's add separate doc about different python envs, motivations, usage examples

2023-07-05 09:39 UTC, TheSuperiorStanislav commented on README.md
> +* `django_migrate_command` migrate command (Default: `migrate`)
The one that uses `django-tenats`

2023-07-13 07:59 UTC, ron8mcr approved these changes

2023-07-13 07:59 UTC, ron8mcr commented on README.md
> +* `docker` is python that is located inside your docker image of service(`python_service`).
```suggestion
* `docker` is python that is located inside your docker image of service (`python_service`).
```

2023-07-13 07:59 UTC, ron8mcr commented on README.md
> +* `python_service` python service name (Default: `web`)
```suggestion
* `python_docker_service` python service name (Default: `web`)
```
What do you think about this renaming? I think this name is more explicit

2023-07-13 07:59 UTC, ron8mcr commented on README.md
> +Run `makemigrations` command and chown created migrations(only for docker env).
```suggestion
Run `makemigrations` command and chown created migrations (only for docker env).
```

2023-07-13 07:59 UTC, ron8mcr commented on README.md
> +Check if there is new migrations or not.
Add note that result should be checked by exit code

2023-07-13 07:59 UTC, ron8mcr commented on README.md
> +Check that generated open_api spec is valid.
Add note that this command uses https://github.com/tfranzel/drf-spectacular and it's default validator

2023-07-13 07:59 UTC, ron8mcr commented on README.md
> +Open database shell with credentials from either local or dev env.
```suggestion
Open database shell with credentials from current django settings.
```
As I do not see any mentions of settings in parameters of this command

2023-07-13 07:59 UTC, ron8mcr commented on saritasa_invocations/django.py
> +    printing.print_success("Checking migrations")
```suggestion
    printing.print_success("Django: Checking migrations")
```

2023-07-13 07:59 UTC, ron8mcr commented on saritasa_invocations/django.py
> +    printing.print_success("Create superuser")
```suggestion
    printing.print_success("Django: Create superuser")
```

2023-07-13 07:59 UTC, ron8mcr commented on saritasa_invocations/python.py
> +    supported_env = tuple(PythonEnv)
```suggestion
    supported_envs = tuple(PythonEnv)
```

2023-07-25 09:00 UTC, denismaitak commented on README.md
> +### FastAPI
FastAPI is capitalized but django, celery, python aren't...

2023-07-25 09:01 UTC, denismaitak approved these changes

2023-07-25 09:29 UTC, NikAzanov approved these changes
As for me, this readme is not very searchable

Let's say I want to find the settings for `inv django.run`, but I can't find anything on `django.run`. And there are many different `run` commands for other modules

But I cannot suggest how to improve it other than

```markdown
### Django

#### django.run

description

#### django.migrate

description
```

But in this case, there is a lot of repetition

2023-07-25 09:57 UTC, merged