Add ability to customize pod command template for k8s invocations
saritasa-nest/saritasa-python-invocations pull request #29
Opened 2023-09-15 09:08 UTC by TheSuperiorStanislav

For example in mircoservice related projects i need to add this selector `--selector=app.kubernetes.io/services=auth`

2023-09-15 12:39 UTC, MrShirokow approved these changes

2023-09-18 01:53 UTC, ron8mcr requested changes

2023-09-18 01:53 UTC, ron8mcr commented on saritasa_invocations/_config.py
> +    pod_command: str = (
`pod_command` is too common name, let's use something like `get_single_pod_name_command` or provide ability to configure only `--selector` and leave `kubectl get pods --no-headers --output jsonpath='{{.items[0].metadata.name}}` as hardcoded part

2023-09-18 04:34 UTC, ron8mcr approved these changes

2023-09-19 08:41 UTC, merged