Alembic invocations
saritasa-nest/saritasa-python-invocations pull request #6
Opened 2023-07-24 05:18 UTC by TheSuperiorStanislav

2023-07-25 09:14 UTC, ron8mcr requested changes

2023-07-25 09:14 UTC, ron8mcr commented on saritasa_invocations/alembic.py
> +    run(context, command=command)
Let's add further instructions for developer like:
* Verify migrations
* Remove alembic's messages

2023-07-25 09:14 UTC, ron8mcr commented on saritasa_invocations/alembic.py
> +        printing.print_success(f"Checking {file_path}")
I think this debug message is redundant. 
> "Checking migration files for adjust messages"

Should be enough

2023-07-25 09:14 UTC, ron8mcr commented on saritasa_invocations/alembic.py
> +    for filename in os.listdir(migrations_folder):
Let's use `pathlib` here and below (start with https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob)

2023-07-25 09:14 UTC, ron8mcr commented on saritasa_invocations/alembic.py
> +        )
```suggestion
        log_files_msg = "\n\t".join(files_to_clean.keys())
        log_messages = "\n".join(adjust_messages)
        saritasa_invocations.print_error(
            f"Adjust messages found in this migration files:\n"
            f"\t{log_files_msg}\n"
            "Ensure that this files does not contain following:\n"
            f"{log_messages}",
        )
```

2023-07-26 09:10 UTC, ron8mcr approved these changes

2023-07-27 02:54 UTC, NikAzanov approved these changes

2023-07-27 03:11 UTC, merged